### Create a new tourist

POST http://{{serverUrl}}:8080/api/v1/tourist
Content-Type: application/json

{
  "name": "John",
  "surname": "Doe",
  "email": "john1.doe@example.com",
  "phoneNumber": "+1234567190",
  "address": "123 Main Street",
  "country": "Germany"
}

###

### Get all tourists
GET http://{{serverUrl}}:8080/api/v1/tourist/all

###

### Get tourist by ID
GET http://{{serverUrl}}:8080/api/v1/tourist/678d0a83c419c90979e9c7af
# Replace {id} with the actual ID of the tourist you want to retrieve

###

### Get tourist by email
GET http://{{serverUrl}}:8080/api/v1/tourist/email/john.smith@example.com

###

### Get tourist by phone number
GET http://{{serverUrl}}:8080/api/v1/tourist/phone/+1234567890

###

### Get tourists by name and surname
GET http://{{serverUrl}}:8080/api/v1/tourist/name/John/surname/Smith

###

### Update tourist by ID
PUT http://{{serverUrl}}:8080/api/v1/tourist/678d0a83c419c90979e9c7af
Content-Type: application/json

{
  "name": "John",
  "surname": "Smith",
  "email": "john.smith@example.com",
  "phoneNumber": "+1234567890",
  "country": "Russia"
}
### Replace {id} with the actual ID of the tourist you want to update

###

### Delete tourist by ID
DELETE http://{{serverUrl}}:8080/api/v1/tourist/678d0a83c419c90979e9c7af
# Replace {id} with the actual ID of the tourist you want to delete