server:
  port: 8080
grpc:
  client:
    touristService:
      address: localhost:8090
      negotiation-type: plaintext
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: 1234
redis:
  host: localhost
  port: 6379
logstash:
  host: localhost
  port: 6000