spring:
  data:
    mongodb:
      database: touristService
      port: 27017
      host: localhost
      auto-index-creation: true
grpc:
  server:
    port: 8090
server:
  port: 8085
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true