spring:
  data:
    mongodb:
      database: touristService
      port: 27017
      host: localhost
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: 1234
grpc:
  server:
    port: 8090
server:
  port: 8085
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
logstash:
  host: localhost
  port: 6000